name: Health Check

on:
  push:
    branches:
      - '*'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstack-osa11-pokemon-app.fly.dev

      - name: Faulty URL test
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://fullstack-osa11-pokemon-app.fly.dev/fault
